name: diabetes-risk-classifier
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - notebook
  - ipykernel
  - imbalanced-learn
  - pip
  - pip:
      - kaggle
